### ISSUE TITLE
Problems with LibreOffice

### ISSUE THREAD

**Issue by Uldgiw** [sonnyp/Junction#56] opened 2022-01-07 14:19 UTC
When opening a docx file with LibreOffice through the Junction interface, Libreoffice always complains that the file is still in use and therefore could only be opened in Read-Only mode. When opening the file the 'normal' way this problem doenst occur.

Let me know if I can provide any additional info.

**Comment by sonnyp** [comment] 2022-01-07 14:24
Hello,

Please share the content of Junction -> Menu -> About Junction -> System

It would also be helpful if you could reproduce the problem from the terminal, and share the output - something like

```
flatpak run re.sonny.Junction ~/Document/example.doc
```

**Comment by Uldgiw** [comment] 2022-01-07 14:26
Junction:
version 1.4.0
programInvocationName /app/bin/re.sonny.Junction
argv --gapplication-service
cwd /home/ludwig
datadir /app/share

Powered by:
GJS 1.70.0
libadwaita 1.0.0
GTK 4.4.1
GLib 2.70.2
flatpak 1.12.2

Environment:
OS Fedora Linux 35 (Workstation Edition)
$XDG_DATA_DIRS /app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share:/run/host/usr/share:/var/lib/snapd/desktop:/var/lib/flatpak/exports/share:/home/ludwig/.local/share/flatpak/exports/share
$PATH /app/bin:/usr/bin
$FLATPAK_ID re.sonny.Junction
$XDG_CURRENT_DESKTOP GNOME
$XDG_SESSION_TYPE wayland

**Comment by Uldgiw** [comment] 2022-01-07 14:31
Strangely when opening the file via

`flatpak run re.sonny.Junction ~/Downloads/test.docx` 

the problem doens't occur.
I've tried it again via the gui way, here the problem still persists.

**Comment by Uldgiw** [comment] 2022-01-07 14:33
Libreoffice was installed via rpm, Junction via flatpak ... in case that matters

**Comment by sonnyp** [comment] 2022-01-08 15:31
I can reproduce the issue – thank you.

**Comment by sonnyp** [comment] 2022-01-09 16:00
Alright, so when launching Junction from Nautilus (right click and open with), the file path is something like `/run/user/1000/doc/e0b414dc/Untitled 1.odt`.

I imagine because Junction is a flatpak app Nautilus mounts the file in the document portal and pass that path to Junction which Junction passes to libreoffice.

Before launching libreoffice from Junction if I run `libreoffice "/run/user/1000/doc/bb83d655/Untitled 1.odt"`, I get the same result.

I have no idea why LibreOffice would report the file being locked, it looks like a bug in libreoffice but anyway, Junction should pass the original path which will solve the problem anyway.

I will have a look and see if it's possible to get it.

**Comment by sonnyp** [comment] 2022-01-09 16:32
Alright, if the flatpak (Junction in our case) has rw access to the path, then the real path is passed.

So, as a workaround for now – you can use Flatseal to give Junction access to home (`All user files` must be toggled on for Junction).

I have found a way to get the real path so I will be able to solve this problem https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Documents.Info

**Comment by Uldgiw** [comment] 2022-01-09 20:33
Thank you for that quick fix,
the workaround works fine for me too :)

Should i close the issue now? bc i've never done an Issue-Report before

**Comment by sonnyp** [comment] 2022-01-09 21:46
No worries, I'll take care of it once the proper fix is release.

**Comment by sonnyp** [comment] 2022-01-20 08:15
Fixed in Junction 1.5.0 available on flathub.

**Comment by sonnyp** [comment] 2022-01-20 12:42
I also reported the bug to Libreoffice https://bugs.documentfoundation.org/show_bug.cgi?id=146874

**Closed by sonnyp** 2022-01-20 12:42 UTC
